<?php

namespace AssignmentsBundle\Repository\Assignment\Checklist;

use ApiBundle\Entity\BranchStation;
use ApiBundle\Entity\Role\BranchStationOriginRole;
use AssignmentsBundle\Entity\Assignment\Checklist\Checklist;

/**
 * ChecklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAssignmentsByStation(BranchStation $station)
    {
        $result = [];
        foreach($station->getAssignments() as $assignment)
        {
            if($assignment instanceof Checklist) {
                $result[] = $assignment;
            }
        }
        return $result;
    }
}
