<?php

namespace WebSocketsBundle\Repository\Notification;

use ApiBundle\Entity\User\AbstractUser;

/**
 * AlertNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param AbstractUser $user
     * @return mixed
     */
    public function getRecordsByUser(AbstractUser $user)
    {
        $qb = $this->createQueryBuilder("AlertNotification");
        $qb->innerJoin('AlertNotification.users','u');

        $qb->where('u = :user')->setParameter(':user', $user);

        $query = $qb->getQuery();
        return $query->getResult();
    }
}
