<?php

namespace WebSocketsBundle\Repository\Notification;

/**
 * AnnouncementNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
