<?php

namespace WebSocketsBundle\Repository\Notification;

/**
 * ReportNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
