<?php

namespace ApiBundle\Repository\User;

use ApiBundle\Entity\Company;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdminsByRepository(Company $company)
    {
        $qb = $this->createQueryBuilder('Admin');
        $qb
            ->where('Admin.company = :company')
            ->setParameter('company', $company);

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
