<?php

namespace ApiBundle\Repository\User;

/**
 * BranchManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
