<?php

namespace ApiBundle\Repository\User;

/**
 * CoManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
