<?php

namespace ApiBundle\Repository\User;

use ApiBundle\Entity\User\BranchManager;
use Symfony\Component\CssSelector\Exception\InternalErrorException;

/**
 * HistoryBranchManagerWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryBranchManagerWorkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $branchManager BranchManager
     * @throws
     * @return mixed
    */
    public function getCurrentRecordManager(BranchManager $branchManager)
    {
        $qb = $this->createQueryBuilder('HistoryBranchManagerWork');
        $qb
            ->where('HistoryBranchManagerWork.branch_manager = :branch_manager')
            ->andWhere('HistoryBranchManagerWork.date_end IS NULL')
            ->setParameter('branch_manager', $branchManager);

        $query = $qb->getQuery();
        if(count($query->getResult()) > 1) {
            throw new InternalErrorException("Several records for one manager are open");
        }
        return $query->getOneOrNullResult();
    }

    /**
     * @return mixed
    */
    public function getOpenShifts()
    {
        $qb = $this->createQueryBuilder('HistoryBranchManagerWork')
            ->innerJoin('HistoryBranchManagerWork.branch_shift', 'bs')
            ->innerJoin('HistoryBranchManagerWork.branch_manager', 'bm')
            ->where('HistoryBranchManagerWork.date_end IS NULL');

        return $qb->getQuery()->getResult();
    }
}
