<?php

namespace ApiBundle\Repository\User;

/**
 * OfficeEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
