ApiBundle\Entity\Notification\CustomNotification:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    title:
      expose: true
    description:
      expose: true
    users:
      expose: true