imports:
  - { resource: paypal.yml }
  - { resource: stripe.yml }
payum:
    security:
        token_storage:
            ApiBundle\Entity\Card\PaymentToken: { doctrine: orm }

    storages:
        ApiBundle\Entity\Card\Payment: { doctrine: orm }

    gateways:
        paypal_express_checkout_and_doctrine_orm:
            factory: paypal_express_checkout
            username:  "%express_checkout_username%"
            password:  "%express_checkout_password%"
            signature: "%express_checkout_signature%"
            sandbox: true
        stripe_checkout:
            factory: stripe_checkout
            publishable_key: "%stripe_publishable_key%"
            secret_key: "%stripe_secret_key%"