let flagsOption = [
    { icon: require('images/flags/Abkhazia.svg'), data_attr: "Abkhazia"},
    { icon: require('images/flags/Afghanistan.svg'), data_attr: "Afghanistan"},
    { icon: require('images/flags/Albania.svg'), data_attr: "Albania"},
    { icon: require('images/flags/Algeria.svg'), data_attr: "Algeria"},
    { icon: require('images/flags/American-Samoa.svg'), data_attr: "American Samoa"},
    { icon: require('images/flags/Andorra.svg'), data_attr: "Andorra"},
    { icon: require('images/flags/Angola.svg'), data_attr: "Angola"},
    { icon: require('images/flags/Anguilla.svg'), data_attr: "Anguilla"},
    { icon: require('images/flags/Antigua-and-Barbuda.svg'), data_attr: "Antigua and Barbuda"},
    { icon: require('images/flags/Argentina.svg'), data_attr: "Argentina"},
    { icon: require('images/flags/Armenia.svg'), data_attr: "Armenia"},
    { icon: require('images/flags/Aruba.svg'), data_attr: "Aruba"},
    { icon: require('images/flags/260-united-kingdom.svg'), data_attr: "Ascension"}, //нет файла
    { icon: require('images/flags/Australia.svg'), data_attr: "Australia"}, 
    { icon: require('images/flags/Australia.svg'), data_attr: "Australian External Territories"}, 
    { icon: require('images/flags/Austria.svg'), data_attr: "Austria"},
    { icon: require('images/flags/Azerbaijan.svg'), data_attr: "Azerbaijan"},
    { icon: require('images/flags/Bahamas.svg'), data_attr: "Bahamas"},
    { icon: require('images/flags/Bahrain.svg'), data_attr: "Bahrain"},
    { icon: require('images/flags/Bangladesh.svg'), data_attr: "Bangladesh"},
    { icon: require('images/flags/Barbados.svg'), data_attr: "Barbados"},
    { icon: require('images/flags/Antigua-and-Barbuda.svg'), data_attr: "Barbuda"},
    { icon: require('images/flags/135-belarus.svg'), data_attr: "Belarus"},
    { icon: require('images/flags/165-belgium.svg'), data_attr: "Belgium"},
    { icon: require('images/flags/078-belize.svg'), data_attr: "Belize"},
    { icon: require('images/flags/060-benin.svg'), data_attr: "Benin"},
    { icon: require('images/flags/081-bermuda.svg'), data_attr: "Bermuda"},
    { icon: require('images/flags/040-bhutan.svg'), data_attr: "Bhutan"},
    { icon: require('images/flags/150-bolivia.svg'), data_attr: "Bolivia"},
    { icon: require('images/flags/132-bosnia-and-herzegovina.svg'), data_attr: "Bosnia and Herzegovina"},
    { icon: require('images/flags/126-botswana.svg'), data_attr: "Botswana"},
    { icon: require('images/flags/255-brazil.svg'), data_attr: "Brazil"},
    { icon: require('images/flags/069-british-indian-ocean-territory.svg'), data_attr: "British Indian Ocean Territory"},
    { icon: require('images/flags/114-british-virgin-islands.svg'), data_attr: "British Virgin Islands"},
    { icon: require('images/flags/119-brunei.svg'), data_attr: "Brunei"},
    { icon: require('images/flags/168-bulgaria.svg'), data_attr: "Bulgaria"},
    { icon: require('images/flags/090-burkina-faso.svg'), data_attr: "Burkina Faso"},
    { icon: require('images/flags/057-burundi.svg'), data_attr: "Burundi"},
    { icon: require('images/flags/159-cambodia.svg'), data_attr: "Cambodia"},
    { icon: require('images/flags/105-cameroon.svg'), data_attr: "Cameroon"},
    { icon: require('images/flags/243-canada.svg'), data_attr: "Canada"},
    { icon: require('images/flags/038-cape-verde.svg'), data_attr: "Cape Verde"},
    { icon: require('images/flags/051-cayman-islands.svg'), data_attr: "Cayman Islands"},
    { icon: require('images/flags/036-central-african-republic.svg'), data_attr: "Central African Republic"},
    { icon: require('images/flags/066-chad.svg'), data_attr: "Chad"},
    { icon: require('images/flags/131-chile.svg'), data_attr: "Chile"},
    { icon: require('images/flags/034-china.svg'), data_attr: "China"},
    { icon: require('images/flags/017-christmas-island.svg'), data_attr: "Christmas Island"},
    { icon: require('images/flags/023-cocos-island.svg'), data_attr: "Cocos-Keeling Islands"},
    { icon: require('images/flags/177-colombia.svg'), data_attr: "Colombia"},
    { icon: require('images/flags/029-comoros.svg'), data_attr: "Comoros"},
    { icon: require('images/flags/157-republic-of-the-congo.svg'), data_attr: "Congo"},
    { icon: require('images/flags/249-democratic-republic-of-congo.svg'), data_attr: "Congo, Dem. Rep. of (Zaire)"},
    { icon: require('images/flags/021-cook-islands.svg'), data_attr: "Cook Islands"},
    { icon: require('images/flags/156-costa-rica.svg'), data_attr: "Costa Rica"},
    { icon: require('images/flags/164-croatia.svg'), data_attr: "Croatia"},
    { icon: require('images/flags/153-cuba.svg'), data_attr: "Cuba"},
    { icon: require('images/flags/116-curacao.svg'), data_attr: "Curacao"},
    { icon: require('images/flags/101-northern-cyprus.svg'), data_attr: "Cyprus"},
    { icon: require('images/flags/149-czech-republic.svg'), data_attr: "Czech Republic"},
    { icon: require('images/flags/174-denmark.svg'), data_attr: "Denmark"},
    { icon: require('images/flags/069-british-indian-ocean-territory.svg'), data_attr: "Diego Garcia"},
    { icon: require('images/flags/068-djibouti.svg'), data_attr: "Djibouti"},
    { icon: require('images/flags/186-dominica.svg'), data_attr: "Dominica"},
    { icon: require('images/flags/047-dominican-republic.svg'), data_attr: "Dominican Republic"},
    { icon: require('images/flags/140-east-timor.svg'), data_attr: "East Timor"},
    { icon: require('images/flags/131-chile.svg'), data_attr: "Easter Island"},
    { icon: require('images/flags/104-ecuador.svg'), data_attr: "Ecuador"},
    { icon: require('images/flags/158-egypt.svg'), data_attr: "Egypt"},
    { icon: require('images/flags/015-el-salvador.svg'), data_attr: "El Salvador"},
    { icon: require('images/flags/189-equatorial-guinea.svg'), data_attr: "Equatorial Guinea"},
    { icon: require('images/flags/065-eritrea.svg'), data_attr: "Eritrea"},
    { icon: require('images/flags/008-estonia.svg'), data_attr: "Estonia"},
    { icon: require('images/flags/005-ethiopia.svg'), data_attr: "Ethiopia"},
    { icon: require('images/flags/215-falkland-islands.svg'), data_attr: "Falkland Islands"},
    { icon: require('images/flags/174-denmark.svg'), data_attr: "Faroe Islands"},
    { icon: require('images/flags/137-fiji.svg'), data_attr: "Fiji"},
    { icon: require('images/flags/125-finland.svg'), data_attr: "Finland"},
    { icon: require('images/flags/195-france.svg'), data_attr: "France"},
    { icon: require('images/flags/195-france.svg'), data_attr: "French Antilles"}, //нет флага
    { icon: require('images/flags/195-france.svg'), data_attr: "French Guiana"},//нет флага
    { icon: require('images/flags/180-french-polynesia.svg'), data_attr: "French Polynesia"},
    { icon: require('images/flags/059-gabon.svg'), data_attr: "Gabon"},
    { icon: require('images/flags/146-gambia.svg'), data_attr: "Gambia"},
    { icon: require('images/flags/256-georgia.svg'), data_attr: "Georgia"},
    { icon: require('images/flags/162-germany.svg'), data_attr: "Germany"},
    { icon: require('images/flags/053-ghana.svg'), data_attr: "Ghana"},
    { icon: require('images/flags/213-gibraltar.svg'), data_attr: "Gibraltar"},
    { icon: require('images/flags/170-greece.svg'), data_attr: "Greece"},
    { icon: require('images/flags/113-greenland.svg'), data_attr: "Greenland"},
    { icon: require('images/flags/210-grenada.svg'), data_attr: "Grenada"},
    { icon: require('images/flags/195-france.svg'), data_attr: "Guadeloupe"}, //нет флага
    { icon: require('images/flags/207-guam.svg'), data_attr: "Guam"},
    { icon: require('images/flags/098-guatemala.svg'), data_attr: "Guatemala"},
    { icon: require('images/flags/110-guinea.svg'), data_attr: "Guinea"},
    { icon: require('images/flags/056-guinea-bissau.svg'), data_attr: "Guinea-Bissau"},
    // { icon: require('images/flags/.svg'), data_attr: "Guyana"}, //нет флага
    { icon: require('images/flags/185-haiti.svg'), data_attr: "Haiti"},
    { icon: require('images/flags/024-honduras.svg'), data_attr: "Honduras"},
    { icon: require('images/flags/183-hong-kong.svg'), data_attr: "Hong Kong SAR China"},
    { icon: require('images/flags/115-hungary.svg'), data_attr: "Hungary"},
    { icon: require('images/flags/080-iceland.svg'), data_attr: "Iceland"},
    { icon: require('images/flags/246-india.svg'), data_attr: "India"},
    { icon: require('images/flags/209-indonesia.svg'), data_attr: "Indonesia"},
    { icon: require('images/flags/136-iran.svg'), data_attr: "Iran"},
    { icon: require('images/flags/020-iraq.svg'), data_attr: "Iraq"},
    { icon: require('images/flags/179-ireland.svg'), data_attr: "Ireland"},
    { icon: require('images/flags/155-israel.svg'), data_attr: "Israel"},
    { icon: require('images/flags/013-italy.svg'), data_attr: "Italy"},
    { icon: require('images/flags/161-ivory-coast.svg'), data_attr: "Ivory Coast"},
    { icon: require('images/flags/037-jamaica.svg'), data_attr: "Jamaica"},
    { icon: require('images/flags/063-japan.svg'), data_attr: "Japan"},
    { icon: require('images/flags/077-jordan.svg'), data_attr: "Jordan"},
    { icon: require('images/flags/074-kazakhstan.svg'), data_attr: "Kazakhstan"},
    { icon: require('images/flags/067-kenya.svg'), data_attr: "Kenya"},
    { icon: require('images/flags/261-kiribati.svg'), data_attr: "Kiribati"},
    { icon: require('images/flags/107-kwait.svg'), data_attr: "Kuwait"},
    { icon: require('images/flags/152-kyrgyzstan.svg'), data_attr: "Kyrgyzstan"},
    { icon: require('images/flags/112-laos.svg'), data_attr: "Laos"},
    { icon: require('images/flags/044-latvia.svg'), data_attr: "Latvia"},
    { icon: require('images/flags/018-lebanon.svg'), data_attr: "Lebanon"},
    { icon: require('images/flags/176-lesotho.svg'), data_attr: "Lesotho"},
    { icon: require('images/flags/169-liberia.svg'), data_attr: "Liberia"},
    { icon: require('images/flags/231-libya.svg'), data_attr: "Libya"},
    { icon: require('images/flags/134-liechtenstein.svg'), data_attr: "Liechtenstein"},
    { icon: require('images/flags/064-lithuania.svg'), data_attr: "Lithuania"},
    { icon: require('images/flags/035-luxembourg.svg'), data_attr: "Luxembourg"},
    { icon: require('images/flags/167-macao.svg'), data_attr: "Macau SAR China"},
    { icon: require('images/flags/236-republic-of-macedonia.svg'), data_attr: "Macedonia"},
    { icon: require('images/flags/242-madagascar.svg'), data_attr: "Madagascar"},
    { icon: require('images/flags/214-malawi.svg'), data_attr: "Malawi"},
    { icon: require('images/flags/118-malasya.svg'), data_attr: "Malaysia"},
    { icon: require('images/flags/225-maldives.svg'), data_attr: "Maldives"},
    { icon: require('images/flags/173-mali.svg'), data_attr: "Mali"},
    { icon: require('images/flags/194-malta.svg'), data_attr: "Malta"},
    { icon: require('images/flags/103-marshall-island.svg'), data_attr: "Marshall Islands"},
    { icon: require('images/flags/201-martinique.svg'), data_attr: "Martinique"},
    { icon: require('images/flags/050-mauritania.svg'), data_attr: "Mauritania"},
    { icon: require('images/flags/001-mauritius.svg'), data_attr: "Mauritius"},
    // { icon: require('images/flags/.svg'), data_attr: "Mayotte"}, //нет флага
    { icon: require('images/flags/252-mexico.svg'), data_attr: "Mexico"},
    { icon: require('images/flags/046-micronesia.svg'), data_attr: "Micronesia"},
    //{ icon: require('images/flags/.svg'), data_attr: "Midway Island"}, //нет флага
    { icon: require('images/flags/212-moldova.svg'), data_attr: "Moldova"},
    { icon: require('images/flags/039-monaco.svg'), data_attr: "Monaco"},
    { icon: require('images/flags/258-mongolia.svg'), data_attr: "Mongolia"},
    { icon: require('images/flags/239-montenegro.svg'), data_attr: "Montenegro"},
    { icon: require('images/flags/043-montserrat.svg'), data_attr: "Montserrat"},
    { icon: require('images/flags/166-morocco.svg'), data_attr: "Morocco"},
    { icon: require('images/flags/058-myanmar.svg'), data_attr: "Myanmar"},
    { icon: require('images/flags/062-namibia.svg'), data_attr: "Namibia"},
    { icon: require('images/flags/228-nauru.svg'), data_attr: "Nauru"},
    { icon: require('images/flags/016-nepal.svg'), data_attr: "Nepal"},
    { icon: require('images/flags/237-netherlands.svg'), data_attr: "Netherlands"},
    // { icon: require('images/flags/.svg'), data_attr: "Netherlands Antilles"}, //no flag
    { icon: require('images/flags/033-saint-kitts-and-nevis.svg'), data_attr: "Nevis"},
    // { icon: require('images/flags/.svg'), data_attr: "New Caledonia"}, //no flag
    { icon: require('images/flags/121-new-zealand.svg'), data_attr: "New Zealand"},
    { icon: require('images/flags/007-nicaragua.svg'), data_attr: "Nicaragua"},
    { icon: require('images/flags/222-niger.svg'), data_attr: "Niger"},
    { icon: require('images/flags/086-nigeria.svg'), data_attr: "Nigeria"},
    { icon: require('images/flags/182-niue.svg'), data_attr: "Niue"},
    { icon: require('images/flags/193-norfolk-island.svg'), data_attr: "Norfolk Island"},
    { icon: require('images/flags/030-north-korea.svg'), data_attr: "North Korea"},
    { icon: require('images/flags/160-northern-marianas-islands.svg'), data_attr: "Northern Mariana Islands"},
    { icon: require('images/flags/143-norway.svg'), data_attr: "Norway"},
    { icon: require('images/flags/004-oman.svg'), data_attr: "Oman"},
    { icon: require('images/flags/100-pakistan.svg'), data_attr: "Pakistan"},
    { icon: require('images/flags/178-palau.svg'), data_attr: "Palau"},
    { icon: require('images/flags/208-palestine.svg'), data_attr: "Palestinian Territory"},
    { icon: require('images/flags/106-panama.svg'), data_attr: "Panama"},
    { icon: require('images/flags/163-papua-new-guinea.svg'), data_attr: "Papua New Guinea"},
    { icon: require('images/flags/041-paraguay.svg'), data_attr: "Paraguay"},
    { icon: require('images/flags/188-peru.svg'), data_attr: "Peru"},
    { icon: require('images/flags/192-philippines.svg'), data_attr: "Philippines"},
    { icon: require('images/flags/211-poland.svg'), data_attr: "Poland"},
    { icon: require('images/flags/224-portugal.svg'), data_attr: "Portugal"},
    { icon: require('images/flags/028-puerto-rico.svg'), data_attr: "Puerto Rico"},
    { icon: require('images/flags/026-qatar.svg'), data_attr: "Qatar"},
    // { icon: require('images/flags/.svg'), data_attr: "Reunion"}, no-flag
    { icon: require('images/flags/109-romania.svg'), data_attr: "Romania"},
    { icon: require('images/flags/248-russia.svg'), data_attr: "Russia"},
    { icon: require('images/flags/206-rwanda.svg'), data_attr: "Rwanda"},
    { icon: require('images/flags/251-samoa.svg'), data_attr: "Samoa"},
    { icon: require('images/flags/097-san-marino.svg'), data_attr: "San Marino"},
    { icon: require('images/flags/133-saudi-arabia.svg'), data_attr: "Saudi Arabia"},
    { icon: require('images/flags/227-senegal.svg'), data_attr: "Senegal"},
    { icon: require('images/flags/071-serbia.svg'), data_attr: "Serbia"},
    { icon: require('images/flags/253-seychelles.svg'), data_attr: "Seychelles"},
    { icon: require('images/flags/092-sierra-leone.svg'), data_attr: "Sierra Leone"},
    { icon: require('images/flags/230-singapore.svg'), data_attr: "Singapore"},
    { icon: require('images/flags/091-slovakia.svg'), data_attr: "Slovakia"},
    { icon: require('images/flags/010-slovenia.svg'), data_attr: "Slovenia"},
    { icon: require('images/flags/085-solomon-islands.svg'), data_attr: "Solomon Islands"},
    { icon: require('images/flags/200-south-africa.svg'), data_attr: "South Africa"},
    // { icon: require('images/flags/.svg'), data_attr: "South Georgia and the South Sandwich Islands"}, //no flag
    { icon: require('images/flags/094-south-korea.svg'), data_attr: "South Korea"},
    { icon: require('images/flags/128-spain.svg'), data_attr: "Spain"},
    { icon: require('images/flags/127-sri-lanka.svg'), data_attr: "Sri Lanka"},
    { icon: require('images/flags/199-sudan.svg'), data_attr: "Sudan"},
    { icon: require('images/flags/076-suriname.svg'), data_attr: "Suriname"},
    { icon: require('images/flags/154-swaziland.svg'), data_attr: "Swaziland"},
    { icon: require('images/flags/184-sweden.svg'), data_attr: "Sweden"},
    { icon: require('images/flags/205-switzerland.svg'), data_attr: "Switzerland"},
    { icon: require('images/flags/022-syria.svg'), data_attr: "Syria"},
    { icon: require('images/flags/202-taiwan.svg'), data_attr: "Taiwan"},
    { icon: require('images/flags/196-tajikistan.svg'), data_attr: "Tajikistan"},
    { icon: require('images/flags/006-tanzania.svg'), data_attr: "Tanzania"},
    { icon: require('images/flags/238-thailand.svg'), data_attr: "Thailand"},
    { icon: require('images/flags/140-east-timor.svg'), data_attr: "Timor Leste"},
    { icon: require('images/flags/073-togo.svg'), data_attr: "Togo"},
    { icon: require('images/flags/235-tokelau.svg'), data_attr: "Tokelau"},
    { icon: require('images/flags/191-tonga.svg'), data_attr: "Tonga"},
    { icon: require('images/flags/181-trinidad-and-tobago.svg'), data_attr: "Trinidad and Tobago"},
    { icon: require('images/flags/049-tunisia.svg'), data_attr: "Tunisia"},
    { icon: require('images/flags/218-turkey.svg'), data_attr: "Turkey"},
    { icon: require('images/flags/229-turkmenistan.svg'), data_attr: "Turkmenistan"},
    { icon: require('images/flags/223-turks-and-caicos.svg'), data_attr: "Turks and Caicos Islands"},
    { icon: require('images/flags/221-tuvalu.svg'), data_attr: "Tuvalu"},
    { icon: require('images/flags/217-virgin-islands.svg'), data_attr: "U.S. Virgin Islands"},
    { icon: require('images/flags/009-uganda.svg'), data_attr: "Uganda"},
    { icon: require('images/flags/145-ukraine.svg'), data_attr: "Ukraine"},
    { icon: require('images/flags/151-united-arab-emirates.svg'), data_attr: "United Arab Emirates"},
    { icon: require('images/flags/260-united-kingdom.svg'), data_attr: "United Kingdom"},
    { icon: require('images/flags/226-united-states.svg'), data_attr: "United States"},
    { icon: require('images/flags/088-uruguay.svg'), data_attr: "Uruguay"},
    { icon: require('images/flags/190-uzbekistn.svg'), data_attr: "Uzbekistan"},
    { icon: require('images/flags/187-vanuatu.svg'), data_attr: "Vanuatu"},
    { icon: require('images/flags/139-venezuela.svg'), data_attr: "Venezuela"},
    { icon: require('images/flags/220-vietnam.svg'), data_attr: "Vietnam"},
    // { icon: require('images/flags/.svg'), data_attr: "Wake Island"}, //no flag
    // { icon: require('images/flags/.svg'), data_attr: "Wallis and Futuna"}, //no flag
    { icon: require('images/flags/232-yemen.svg'), data_attr: "Yemen"},
    { icon: require('images/flags/032-zambia.svg'), data_attr: "Zambia"},
    // { icon: require('images/flags/.svg'), data_attr: "Zanzibar"},  //no flag
    { icon: require('images/flags/011-zimbabwe.svg'), data_attr: "Zimbabwe"}
]

export default flagsOption;