<?php

namespace AssignmentsBundle\Repository\Assignment\Question\AnswerList;

/**
 * QuestionPossibleAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionPossibleAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
