<?php

namespace AssignmentsBundle\Repository\Assignment\Question\AnswerList;

use ApiBundle\Entity\BranchStation;
use AssignmentsBundle\Entity\Assignment\Question\AnswerList\QuestionAnswerList;

/**
 * QuestionAnswerListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionAnswerListRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAssignmentsByStation(BranchStation $station)
    {
        $result = [];
        foreach($station->getAssignments() as $assignment)
        {
            if($assignment instanceof QuestionAnswerList) {
                $result[] = $assignment;
            }
        }
        return $result;
    }
}
