AssignmentsBundle\Entity\Assignment\Notification:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    title:
      expose: true
    description:
      expose: true
    role:
      expose: true
    snooze_count:
      expose: true
    snooze_until:
      expose: true
    working:
      expose: true