<?php

namespace AssignmentsBundle\Repository\Notification;

/**
 * DeviceNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewNotifications()
    {
        $now = new \DateTime();
        $today = new \DateTime();
        $today = $today->format('Y-m-d');

        $qb = $this->createQueryBuilder('DeviceNotification');
        $qb
            ->where(':now >= DeviceNotification.start_time')
            ->andWhere(':now <= DeviceNotification.end_time')
            ->andWhere($qb->expr()->orX(
                'DeviceNotification.lastSentDate IS NULL',
                'DATE(DeviceNotification.lastSentDate) != :today'
            ))
            ->andWhere('DeviceNotification.enabled = 1')
            ->setParameter("now", $now)
            ->setParameter("today", $today);

        $query = $qb->getQuery();

        return $query->getResult();

    }
}
