<?php

namespace AssignmentsBundle\Repository\Notification;

use ApiBundle\Entity\BranchStation;

/**
 * DeviceNotificationStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceNotificationStationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $station BranchStation
     * @param $date_start
     * @param $date_end
     * @return mixed
     */
    public function getNotificationsByStation($station, $date_start, $date_end)
    {
        $qb = $this->createQueryBuilder('DeviceNotificationStation');
        $qb->innerJoin('DeviceNotificationStation.station', 's');
        $qb->andWhere('s = :station')
            ->andWhere('TIMESTAMPDIFF(second, :date_start, DeviceNotificationStation.start_time) >= 0')
            ->andWhere('TIMESTAMPDIFF(second, DeviceNotificationStation.start_time, :date_end) >= 0')
            ->setParameter('station', $station)
            ->setParameter('date_start', $date_start)
            ->setParameter('date_end', $date_end);

        $query = $qb->getQuery();
        return $query->getResult();
    }
}
