<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20171110100635 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE branch (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, supervisor_id INT DEFAULT NULL, geographical_area_id INT DEFAULT NULL, name VARCHAR(80) NOT NULL, INDEX IDX_BB861B1F979B1AD6 (company_id), INDEX IDX_BB861B1F19E9AC5F (supervisor_id), UNIQUE INDEX UNIQ_BB861B1F9F16EA29 (geographical_area_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch_shift (id INT AUTO_INCREMENT NOT NULL, branch_id INT DEFAULT NULL, shift_day_id INT DEFAULT NULL, time_open TIME NOT NULL, time_close TIME NOT NULL, limit_time_open INT NOT NULL, INDEX IDX_CBBA3912DCD6CC49 (branch_id), INDEX IDX_CBBA3912851AD333 (shift_day_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch_station (id INT AUTO_INCREMENT NOT NULL, branch_id INT DEFAULT NULL, name VARCHAR(80) NOT NULL, pin INT DEFAULT NULL, pin_expire DATETIME DEFAULT NULL, device_code VARCHAR(255) DEFAULT NULL, INDEX IDX_84CD3CBFDCD6CC49 (branch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE card (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(80) NOT NULL, number VARCHAR(16) NOT NULL, month VARCHAR(2) NOT NULL, year VARCHAR(4) NOT NULL, cvv VARCHAR(10) NOT NULL, INDEX IDX_161498D3A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE history_card_payment (id INT AUTO_INCREMENT NOT NULL, card_id INT DEFAULT NULL, payment_amount DOUBLE PRECISION NOT NULL, INDEX IDX_EC2FD804ACC9A20 (card_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, geographical_area_id INT DEFAULT NULL, time_zone_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, date_format_id INT DEFAULT NULL, subcategory_id INT DEFAULT NULL, name VARCHAR(80) NOT NULL, week_start_on SMALLINT DEFAULT NULL, overtime_hourly_rate DOUBLE PRECISION DEFAULT NULL, weekend_rate DOUBLE PRECISION DEFAULT NULL, plan VARCHAR(255) NOT NULL, plan_payed_until DATETIME NOT NULL, UNIQUE INDEX UNIQ_4FBF094F9F16EA29 (geographical_area_id), INDEX IDX_4FBF094FCBAB9ECD (time_zone_id), INDEX IDX_4FBF094F38248176 (currency_id), INDEX IDX_4FBF094FE95FC5B1 (date_format_id), INDEX IDX_4FBF094F5DC6FE57 (subcategory_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(80) NOT NULL, phone_code VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency (id INT AUTO_INCREMENT NOT NULL, currency VARCHAR(80) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE date_format (id INT AUTO_INCREMENT NOT NULL, date_format VARCHAR(80) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE emergency_phone (id INT AUTO_INCREMENT NOT NULL, country_id INT DEFAULT NULL, phone_number VARCHAR(20) NOT NULL, type VARCHAR(20) NOT NULL, INDEX IDX_C4418F20F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE employee (id INT AUTO_INCREMENT NOT NULL, geographical_area_id INT DEFAULT NULL, avatar_id INT DEFAULT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, phone_number VARCHAR(20) NOT NULL, family_status VARCHAR(20) NOT NULL, hourly_rate DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_5D9F75A19F16EA29 (geographical_area_id), UNIQUE INDEX UNIQ_5D9F75A186383B10 (avatar_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE employee_branch (employee_id INT NOT NULL, branch_id INT NOT NULL, INDEX IDX_92B7DF8A8C03F15C (employee_id), INDEX IDX_92B7DF8ADCD6CC49 (branch_id), PRIMARY KEY(employee_id, branch_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE employees_branch_shifts (employee_id INT NOT NULL, branch_shift_id INT NOT NULL, INDEX IDX_D6D94B5E8C03F15C (employee_id), INDEX IDX_D6D94B5E5CD365CD (branch_shift_id), PRIMARY KEY(employee_id, branch_shift_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, size NUMERIC(10, 0) NOT NULL, file_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file_avatar (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geographical_area (id INT AUTO_INCREMENT NOT NULL, country_id INT DEFAULT NULL, region VARCHAR(80) NOT NULL, city VARCHAR(80) NOT NULL, street_address VARCHAR(100) NOT NULL, zip VARCHAR(10) NOT NULL, INDEX IDX_C3AB7498F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE history_employee_role (id INT AUTO_INCREMENT NOT NULL, employee_id INT DEFAULT NULL, role_id INT DEFAULT NULL, branch_shift_id INT DEFAULT NULL, date_start DATETIME NOT NULL, date_end DATETIME DEFAULT NULL, INDEX IDX_C8EB1B4A8C03F15C (employee_id), INDEX IDX_C8EB1B4AD60322AC (role_id), INDEX IDX_C8EB1B4A5CD365CD (branch_shift_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE industry_category (id INT AUTO_INCREMENT NOT NULL, category VARCHAR(80) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE access_token (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_B6A2DD685F37A13B (token), INDEX IDX_B6A2DD6819EB6921 (client_id), INDEX IDX_B6A2DD68A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auth_code (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, redirect_uri LONGTEXT NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_5933D02C5F37A13B (token), INDEX IDX_5933D02C19EB6921 (client_id), INDEX IDX_5933D02CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, random_id VARCHAR(255) NOT NULL, redirect_uris LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', secret VARCHAR(255) NOT NULL, allowed_grant_types LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_token (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_C74F21955F37A13B (token), INDEX IDX_C74F219519EB6921 (client_id), INDEX IDX_C74F2195A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE report (id INT AUTO_INCREMENT NOT NULL, branch_shift_id INT DEFAULT NULL, archive TINYINT(1) NOT NULL, deleted TINYINT(1) NOT NULL, date_deleted DATETIME DEFAULT NULL, is_read TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_C42F77845CD365CD (branch_shift_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cashier_report (id INT NOT NULL, branch_station_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, payment_method VARCHAR(20) NOT NULL, amount DOUBLE PRECISION NOT NULL, INDEX IDX_3EA2C6523E65BB6B (branch_station_id), INDEX IDX_3EA2C65238248176 (currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commodity_report (id INT NOT NULL, branch_station_id INT DEFAULT NULL, title VARCHAR(80) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_B165DF6E3E65BB6B (branch_station_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE end_of_day_report (id INT NOT NULL, company_id INT DEFAULT NULL, workday_start_time TIME NOT NULL, workday_end_time TIME DEFAULT NULL, employee_total_work_time INT NOT NULL, employee_budget DOUBLE PRECISION NOT NULL, ratio DOUBLE PRECISION NOT NULL, INDEX IDX_6B6B75B6979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE end_of_shift_report (id INT NOT NULL, workday_start_time TIME NOT NULL, workday_end_time TIME DEFAULT NULL, employee_total_work_time INT NOT NULL, employee_budget DOUBLE PRECISION NOT NULL, ratio DOUBLE PRECISION NOT NULL, closed TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE problem_report (id INT NOT NULL, branch_station_id INT DEFAULT NULL, title VARCHAR(80) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_85B305CB3E65BB6B (branch_station_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch_station_role (id INT AUTO_INCREMENT NOT NULL, branch_station_id INT DEFAULT NULL, role VARCHAR(80) NOT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_E4BE7AF13E65BB6B (branch_station_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch_station_origin_role (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch_station_temp_role (id INT NOT NULL, origin_role_id INT DEFAULT NULL, INDEX IDX_99FEDB48637437C1 (origin_role_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE security_recent_login (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, date DATETIME NOT NULL, country_code VARCHAR(255) DEFAULT NULL, country_name VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, ip VARCHAR(255) DEFAULT NULL, INDEX IDX_C822A6E1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sessions (sess_id VARCHAR(128) NOT NULL, sess_data LONGBLOB NOT NULL, sess_time INT NOT NULL, sess_lifetime INT NOT NULL, PRIMARY KEY(sess_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shift_day (id INT AUTO_INCREMENT NOT NULL, day INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE schedule_shifts (shift_day_id INT NOT NULL, branch_id INT NOT NULL, INDEX IDX_7F3C3530851AD333 (shift_day_id), INDEX IDX_7F3C3530DCD6CC49 (branch_id), PRIMARY KEY(shift_day_id, branch_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subcategory (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, subcategory VARCHAR(80) NOT NULL, INDEX IDX_DDCA44812469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE time_zone (id INT AUTO_INCREMENT NOT NULL, time_zone VARCHAR(80) NOT NULL, offset VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, avatar_id INT DEFAULT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', login VARCHAR(50) DEFAULT NULL, first_name VARCHAR(80) DEFAULT NULL, last_name VARCHAR(80) DEFAULT NULL, phone_number VARCHAR(20) DEFAULT NULL, locale VARCHAR(20) NOT NULL, email VARCHAR(255) DEFAULT NULL, email_canonical VARCHAR(255) DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, username_canonical VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649C05FB297 (confirmation_token), UNIQUE INDEX UNIQ_8D93D649A0D96FBF (email_canonical), INDEX IDX_8D93D649979B1AD6 (company_id), UNIQUE INDEX UNIQ_8D93D64986383B10 (avatar_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users_groups (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_FF8AB7E0A76ED395 (user_id), INDEX IDX_FF8AB7E0FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_admin (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_branch_manager (id INT NOT NULL, branch_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_8A553EEEDCD6CC49 (branch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_co_manager (id INT NOT NULL, branch_id INT DEFAULT NULL, INDEX IDX_16A94431DCD6CC49 (branch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_device (id INT NOT NULL, station_id INT DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, INDEX IDX_6C7DADB321BDB235 (station_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_8F02BF9D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_office_employee (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_owner (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_supervisor (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer (id INT AUTO_INCREMENT NOT NULL, assignment_id INT DEFAULT NULL, employee_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_E2FC6A38D19302F8 (assignment_id), INDEX IDX_E2FC6A388C03F15C (employee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer_check_list (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer_check_list_done_tasks (id INT AUTO_INCREMENT NOT NULL, checklist_id INT DEFAULT NULL, task_id INT DEFAULT NULL, INDEX IDX_6F82122EB16D08A7 (checklist_id), INDEX IDX_6F82122E8DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_question_answer_list (id INT NOT NULL, answer_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_8AECFE59AA334807 (answer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer_question_numeric (id INT NOT NULL, answer VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer_question_range (id INT NOT NULL, range_x INT NOT NULL, range_y INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer_question_text (id INT NOT NULL, answer VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer_question_yes_no (id INT NOT NULL, answer TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_answer_standard_task (id INT NOT NULL, answer TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `assignment` (id INT AUTO_INCREMENT NOT NULL, role_id INT DEFAULT NULL, priority INT NOT NULL, importance INT NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, repeat_unit INT DEFAULT NULL, snooze_count INT NOT NULL, snooze_time TIME DEFAULT NULL, snooze_until DATETIME DEFAULT NULL, snooze_max INT NOT NULL, title VARCHAR(255) NOT NULL, view_time INT NOT NULL, last_sent_date DATE DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_30C544BAD60322AC (role_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_checklist (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_checklist_tasks (id INT AUTO_INCREMENT NOT NULL, checklist_id INT DEFAULT NULL, task VARCHAR(255) NOT NULL, INDEX IDX_4BAA92D1B16D08A7 (checklist_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_message (id INT NOT NULL, description LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_notification (id INT NOT NULL, description LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_question_list (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_question_list_possible_answer (id INT AUTO_INCREMENT NOT NULL, question_id INT DEFAULT NULL, answer VARCHAR(255) NOT NULL, INDEX IDX_8F53778B1E27F6BF (question_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_question_numeric (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_question_range (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_question_text (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_question_yes_no (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assignment_standard_task (id INT NOT NULL, description LONGTEXT NOT NULL, working_on_it TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device_notification (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, view_time INT NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, repeat_unit INT DEFAULT NULL, last_sent_date DATE DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device_notification_branch (id INT NOT NULL, branch_id INT DEFAULT NULL, INDEX IDX_89D0C121DCD6CC49 (branch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device_notification_message (id INT NOT NULL, employee_id INT DEFAULT NULL, INDEX IDX_77EE7B0E8C03F15C (employee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device_notification_role (id INT NOT NULL, role_id INT DEFAULT NULL, INDEX IDX_5F5B5FF7D60322AC (role_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device_notification_station (id INT NOT NULL, station_id INT DEFAULT NULL, INDEX IDX_5E6AB3C021BDB235 (station_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, is_read TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_BF5476CAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification_report (id INT NOT NULL, report_id INT DEFAULT NULL, INDEX IDX_8889D94BD2A4C0 (report_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F19E9AC5F FOREIGN KEY (supervisor_id) REFERENCES user_supervisor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F9F16EA29 FOREIGN KEY (geographical_area_id) REFERENCES geographical_area (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE branch_shift ADD CONSTRAINT FK_CBBA3912DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch_shift ADD CONSTRAINT FK_CBBA3912851AD333 FOREIGN KEY (shift_day_id) REFERENCES shift_day (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch_station ADD CONSTRAINT FK_84CD3CBFDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE history_card_payment ADD CONSTRAINT FK_EC2FD804ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F9F16EA29 FOREIGN KEY (geographical_area_id) REFERENCES geographical_area (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FCBAB9ECD FOREIGN KEY (time_zone_id) REFERENCES time_zone (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F38248176 FOREIGN KEY (currency_id) REFERENCES currency (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FE95FC5B1 FOREIGN KEY (date_format_id) REFERENCES date_format (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F5DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES subcategory (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE emergency_phone ADD CONSTRAINT FK_C4418F20F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A19F16EA29 FOREIGN KEY (geographical_area_id) REFERENCES geographical_area (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A186383B10 FOREIGN KEY (avatar_id) REFERENCES file_avatar (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee_branch ADD CONSTRAINT FK_92B7DF8A8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employee_branch ADD CONSTRAINT FK_92B7DF8ADCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employees_branch_shifts ADD CONSTRAINT FK_D6D94B5E8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employees_branch_shifts ADD CONSTRAINT FK_D6D94B5E5CD365CD FOREIGN KEY (branch_shift_id) REFERENCES branch_shift (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE file_avatar ADD CONSTRAINT FK_AE605490BF396750 FOREIGN KEY (id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE geographical_area ADD CONSTRAINT FK_C3AB7498F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE history_employee_role ADD CONSTRAINT FK_C8EB1B4A8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE history_employee_role ADD CONSTRAINT FK_C8EB1B4AD60322AC FOREIGN KEY (role_id) REFERENCES branch_station_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE history_employee_role ADD CONSTRAINT FK_C8EB1B4A5CD365CD FOREIGN KEY (branch_shift_id) REFERENCES branch_shift (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD6819EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD68A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE auth_code ADD CONSTRAINT FK_5933D02C19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE auth_code ADD CONSTRAINT FK_5933D02CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F219519EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F2195A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F77845CD365CD FOREIGN KEY (branch_shift_id) REFERENCES branch_shift (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cashier_report ADD CONSTRAINT FK_3EA2C6523E65BB6B FOREIGN KEY (branch_station_id) REFERENCES branch_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cashier_report ADD CONSTRAINT FK_3EA2C65238248176 FOREIGN KEY (currency_id) REFERENCES currency (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE cashier_report ADD CONSTRAINT FK_3EA2C652BF396750 FOREIGN KEY (id) REFERENCES report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commodity_report ADD CONSTRAINT FK_B165DF6E3E65BB6B FOREIGN KEY (branch_station_id) REFERENCES branch_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commodity_report ADD CONSTRAINT FK_B165DF6EBF396750 FOREIGN KEY (id) REFERENCES report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE end_of_day_report ADD CONSTRAINT FK_6B6B75B6979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE end_of_day_report ADD CONSTRAINT FK_6B6B75B6BF396750 FOREIGN KEY (id) REFERENCES report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE end_of_shift_report ADD CONSTRAINT FK_48C758F4BF396750 FOREIGN KEY (id) REFERENCES report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE problem_report ADD CONSTRAINT FK_85B305CB3E65BB6B FOREIGN KEY (branch_station_id) REFERENCES branch_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE problem_report ADD CONSTRAINT FK_85B305CBBF396750 FOREIGN KEY (id) REFERENCES report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch_station_role ADD CONSTRAINT FK_E4BE7AF13E65BB6B FOREIGN KEY (branch_station_id) REFERENCES branch_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch_station_origin_role ADD CONSTRAINT FK_5C080B78BF396750 FOREIGN KEY (id) REFERENCES branch_station_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch_station_temp_role ADD CONSTRAINT FK_99FEDB48637437C1 FOREIGN KEY (origin_role_id) REFERENCES branch_station_origin_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branch_station_temp_role ADD CONSTRAINT FK_99FEDB48BF396750 FOREIGN KEY (id) REFERENCES branch_station_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE security_recent_login ADD CONSTRAINT FK_C822A6E1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE schedule_shifts ADD CONSTRAINT FK_7F3C3530851AD333 FOREIGN KEY (shift_day_id) REFERENCES shift_day (id)');
        $this->addSql('ALTER TABLE schedule_shifts ADD CONSTRAINT FK_7F3C3530DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)');
        $this->addSql('ALTER TABLE subcategory ADD CONSTRAINT FK_DDCA44812469DE2 FOREIGN KEY (category_id) REFERENCES industry_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64986383B10 FOREIGN KEY (avatar_id) REFERENCES file_avatar (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT FK_FF8AB7E0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT FK_FF8AB7E0FE54D947 FOREIGN KEY (group_id) REFERENCES user_group (id)');
        $this->addSql('ALTER TABLE user_admin ADD CONSTRAINT FK_6ACCF62EBF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_branch_manager ADD CONSTRAINT FK_8A553EEEDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_branch_manager ADD CONSTRAINT FK_8A553EEEBF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_co_manager ADD CONSTRAINT FK_16A94431DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_co_manager ADD CONSTRAINT FK_16A94431BF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB321BDB235 FOREIGN KEY (station_id) REFERENCES branch_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB3BF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_office_employee ADD CONSTRAINT FK_D7E565F1BF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_owner ADD CONSTRAINT FK_2DA21D24BF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_supervisor ADD CONSTRAINT FK_EAF65414BF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_answer ADD CONSTRAINT FK_E2FC6A38D19302F8 FOREIGN KEY (assignment_id) REFERENCES `assignment` (id)');
        $this->addSql('ALTER TABLE assignment_answer ADD CONSTRAINT FK_E2FC6A388C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE assignment_answer_check_list ADD CONSTRAINT FK_27585093BF396750 FOREIGN KEY (id) REFERENCES assignment_answer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_answer_check_list_done_tasks ADD CONSTRAINT FK_6F82122EB16D08A7 FOREIGN KEY (checklist_id) REFERENCES assignment_answer_check_list (id)');
        $this->addSql('ALTER TABLE assignment_answer_check_list_done_tasks ADD CONSTRAINT FK_6F82122E8DB60186 FOREIGN KEY (task_id) REFERENCES assignment_checklist_tasks (id)');
        $this->addSql('ALTER TABLE assignment_question_answer_list ADD CONSTRAINT FK_8AECFE59AA334807 FOREIGN KEY (answer_id) REFERENCES assignment_question_list_possible_answer (id)');
        $this->addSql('ALTER TABLE assignment_question_answer_list ADD CONSTRAINT FK_8AECFE59BF396750 FOREIGN KEY (id) REFERENCES assignment_answer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_answer_question_numeric ADD CONSTRAINT FK_1142C8C5BF396750 FOREIGN KEY (id) REFERENCES assignment_answer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_answer_question_range ADD CONSTRAINT FK_65B5339BF396750 FOREIGN KEY (id) REFERENCES assignment_answer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_answer_question_text ADD CONSTRAINT FK_58C8550FBF396750 FOREIGN KEY (id) REFERENCES assignment_answer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_answer_question_yes_no ADD CONSTRAINT FK_A4B4F4BDBF396750 FOREIGN KEY (id) REFERENCES assignment_answer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_answer_standard_task ADD CONSTRAINT FK_70FA2EBFBF396750 FOREIGN KEY (id) REFERENCES assignment_answer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `assignment` ADD CONSTRAINT FK_30C544BAD60322AC FOREIGN KEY (role_id) REFERENCES branch_station_role (id)');
        $this->addSql('ALTER TABLE assignment_checklist ADD CONSTRAINT FK_917A69C8BF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_checklist_tasks ADD CONSTRAINT FK_4BAA92D1B16D08A7 FOREIGN KEY (checklist_id) REFERENCES assignment_checklist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_message ADD CONSTRAINT FK_D5837D86BF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_notification ADD CONSTRAINT FK_F32B34F8BF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_question_list ADD CONSTRAINT FK_D2BD3B35BF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_question_list_possible_answer ADD CONSTRAINT FK_8F53778B1E27F6BF FOREIGN KEY (question_id) REFERENCES assignment_question_list (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_question_numeric ADD CONSTRAINT FK_B78C4850BF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_question_range ADD CONSTRAINT FK_D6CE73FFBF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_question_text ADD CONSTRAINT FK_ADFE64EABF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_question_yes_no ADD CONSTRAINT FK_D6630618BF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment_standard_task ADD CONSTRAINT FK_85CC1F5ABF396750 FOREIGN KEY (id) REFERENCES `assignment` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE device_notification_branch ADD CONSTRAINT FK_89D0C121DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)');
        $this->addSql('ALTER TABLE device_notification_branch ADD CONSTRAINT FK_89D0C121BF396750 FOREIGN KEY (id) REFERENCES device_notification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE device_notification_message ADD CONSTRAINT FK_77EE7B0E8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE device_notification_message ADD CONSTRAINT FK_77EE7B0EBF396750 FOREIGN KEY (id) REFERENCES device_notification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE device_notification_role ADD CONSTRAINT FK_5F5B5FF7D60322AC FOREIGN KEY (role_id) REFERENCES branch_station_role (id)');
        $this->addSql('ALTER TABLE device_notification_role ADD CONSTRAINT FK_5F5B5FF7BF396750 FOREIGN KEY (id) REFERENCES device_notification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE device_notification_station ADD CONSTRAINT FK_5E6AB3C021BDB235 FOREIGN KEY (station_id) REFERENCES branch_station (id)');
        $this->addSql('ALTER TABLE device_notification_station ADD CONSTRAINT FK_5E6AB3C0BF396750 FOREIGN KEY (id) REFERENCES device_notification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification_report ADD CONSTRAINT FK_8889D94BD2A4C0 FOREIGN KEY (report_id) REFERENCES report (id)');
        $this->addSql('ALTER TABLE notification_report ADD CONSTRAINT FK_8889D9BF396750 FOREIGN KEY (id) REFERENCES notification (id) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE branch_shift DROP FOREIGN KEY FK_CBBA3912DCD6CC49');
        $this->addSql('ALTER TABLE branch_station DROP FOREIGN KEY FK_84CD3CBFDCD6CC49');
        $this->addSql('ALTER TABLE employee_branch DROP FOREIGN KEY FK_92B7DF8ADCD6CC49');
        $this->addSql('ALTER TABLE schedule_shifts DROP FOREIGN KEY FK_7F3C3530DCD6CC49');
        $this->addSql('ALTER TABLE user_branch_manager DROP FOREIGN KEY FK_8A553EEEDCD6CC49');
        $this->addSql('ALTER TABLE user_co_manager DROP FOREIGN KEY FK_16A94431DCD6CC49');
        $this->addSql('ALTER TABLE device_notification_branch DROP FOREIGN KEY FK_89D0C121DCD6CC49');
        $this->addSql('ALTER TABLE employees_branch_shifts DROP FOREIGN KEY FK_D6D94B5E5CD365CD');
        $this->addSql('ALTER TABLE history_employee_role DROP FOREIGN KEY FK_C8EB1B4A5CD365CD');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F77845CD365CD');
        $this->addSql('ALTER TABLE cashier_report DROP FOREIGN KEY FK_3EA2C6523E65BB6B');
        $this->addSql('ALTER TABLE commodity_report DROP FOREIGN KEY FK_B165DF6E3E65BB6B');
        $this->addSql('ALTER TABLE problem_report DROP FOREIGN KEY FK_85B305CB3E65BB6B');
        $this->addSql('ALTER TABLE branch_station_role DROP FOREIGN KEY FK_E4BE7AF13E65BB6B');
        $this->addSql('ALTER TABLE user_device DROP FOREIGN KEY FK_6C7DADB321BDB235');
        $this->addSql('ALTER TABLE device_notification_station DROP FOREIGN KEY FK_5E6AB3C021BDB235');
        $this->addSql('ALTER TABLE history_card_payment DROP FOREIGN KEY FK_EC2FD804ACC9A20');
        $this->addSql('ALTER TABLE branch DROP FOREIGN KEY FK_BB861B1F979B1AD6');
        $this->addSql('ALTER TABLE end_of_day_report DROP FOREIGN KEY FK_6B6B75B6979B1AD6');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649979B1AD6');
        $this->addSql('ALTER TABLE emergency_phone DROP FOREIGN KEY FK_C4418F20F92F3E70');
        $this->addSql('ALTER TABLE geographical_area DROP FOREIGN KEY FK_C3AB7498F92F3E70');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F38248176');
        $this->addSql('ALTER TABLE cashier_report DROP FOREIGN KEY FK_3EA2C65238248176');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FE95FC5B1');
        $this->addSql('ALTER TABLE employee_branch DROP FOREIGN KEY FK_92B7DF8A8C03F15C');
        $this->addSql('ALTER TABLE employees_branch_shifts DROP FOREIGN KEY FK_D6D94B5E8C03F15C');
        $this->addSql('ALTER TABLE history_employee_role DROP FOREIGN KEY FK_C8EB1B4A8C03F15C');
        $this->addSql('ALTER TABLE assignment_answer DROP FOREIGN KEY FK_E2FC6A388C03F15C');
        $this->addSql('ALTER TABLE device_notification_message DROP FOREIGN KEY FK_77EE7B0E8C03F15C');
        $this->addSql('ALTER TABLE file_avatar DROP FOREIGN KEY FK_AE605490BF396750');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A186383B10');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64986383B10');
        $this->addSql('ALTER TABLE branch DROP FOREIGN KEY FK_BB861B1F9F16EA29');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F9F16EA29');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A19F16EA29');
        $this->addSql('ALTER TABLE subcategory DROP FOREIGN KEY FK_DDCA44812469DE2');
        $this->addSql('ALTER TABLE access_token DROP FOREIGN KEY FK_B6A2DD6819EB6921');
        $this->addSql('ALTER TABLE auth_code DROP FOREIGN KEY FK_5933D02C19EB6921');
        $this->addSql('ALTER TABLE refresh_token DROP FOREIGN KEY FK_C74F219519EB6921');
        $this->addSql('ALTER TABLE cashier_report DROP FOREIGN KEY FK_3EA2C652BF396750');
        $this->addSql('ALTER TABLE commodity_report DROP FOREIGN KEY FK_B165DF6EBF396750');
        $this->addSql('ALTER TABLE end_of_day_report DROP FOREIGN KEY FK_6B6B75B6BF396750');
        $this->addSql('ALTER TABLE end_of_shift_report DROP FOREIGN KEY FK_48C758F4BF396750');
        $this->addSql('ALTER TABLE problem_report DROP FOREIGN KEY FK_85B305CBBF396750');
        $this->addSql('ALTER TABLE notification_report DROP FOREIGN KEY FK_8889D94BD2A4C0');
        $this->addSql('ALTER TABLE history_employee_role DROP FOREIGN KEY FK_C8EB1B4AD60322AC');
        $this->addSql('ALTER TABLE branch_station_origin_role DROP FOREIGN KEY FK_5C080B78BF396750');
        $this->addSql('ALTER TABLE branch_station_temp_role DROP FOREIGN KEY FK_99FEDB48BF396750');
        $this->addSql('ALTER TABLE `assignment` DROP FOREIGN KEY FK_30C544BAD60322AC');
        $this->addSql('ALTER TABLE device_notification_role DROP FOREIGN KEY FK_5F5B5FF7D60322AC');
        $this->addSql('ALTER TABLE branch_station_temp_role DROP FOREIGN KEY FK_99FEDB48637437C1');
        $this->addSql('ALTER TABLE branch_shift DROP FOREIGN KEY FK_CBBA3912851AD333');
        $this->addSql('ALTER TABLE schedule_shifts DROP FOREIGN KEY FK_7F3C3530851AD333');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F5DC6FE57');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FCBAB9ECD');
        $this->addSql('ALTER TABLE card DROP FOREIGN KEY FK_161498D3A76ED395');
        $this->addSql('ALTER TABLE access_token DROP FOREIGN KEY FK_B6A2DD68A76ED395');
        $this->addSql('ALTER TABLE auth_code DROP FOREIGN KEY FK_5933D02CA76ED395');
        $this->addSql('ALTER TABLE refresh_token DROP FOREIGN KEY FK_C74F2195A76ED395');
        $this->addSql('ALTER TABLE security_recent_login DROP FOREIGN KEY FK_C822A6E1A76ED395');
        $this->addSql('ALTER TABLE users_groups DROP FOREIGN KEY FK_FF8AB7E0A76ED395');
        $this->addSql('ALTER TABLE user_admin DROP FOREIGN KEY FK_6ACCF62EBF396750');
        $this->addSql('ALTER TABLE user_branch_manager DROP FOREIGN KEY FK_8A553EEEBF396750');
        $this->addSql('ALTER TABLE user_co_manager DROP FOREIGN KEY FK_16A94431BF396750');
        $this->addSql('ALTER TABLE user_device DROP FOREIGN KEY FK_6C7DADB3BF396750');
        $this->addSql('ALTER TABLE user_office_employee DROP FOREIGN KEY FK_D7E565F1BF396750');
        $this->addSql('ALTER TABLE user_owner DROP FOREIGN KEY FK_2DA21D24BF396750');
        $this->addSql('ALTER TABLE user_supervisor DROP FOREIGN KEY FK_EAF65414BF396750');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE users_groups DROP FOREIGN KEY FK_FF8AB7E0FE54D947');
        $this->addSql('ALTER TABLE branch DROP FOREIGN KEY FK_BB861B1F19E9AC5F');
        $this->addSql('ALTER TABLE assignment_answer_check_list DROP FOREIGN KEY FK_27585093BF396750');
        $this->addSql('ALTER TABLE assignment_question_answer_list DROP FOREIGN KEY FK_8AECFE59BF396750');
        $this->addSql('ALTER TABLE assignment_answer_question_numeric DROP FOREIGN KEY FK_1142C8C5BF396750');
        $this->addSql('ALTER TABLE assignment_answer_question_range DROP FOREIGN KEY FK_65B5339BF396750');
        $this->addSql('ALTER TABLE assignment_answer_question_text DROP FOREIGN KEY FK_58C8550FBF396750');
        $this->addSql('ALTER TABLE assignment_answer_question_yes_no DROP FOREIGN KEY FK_A4B4F4BDBF396750');
        $this->addSql('ALTER TABLE assignment_answer_standard_task DROP FOREIGN KEY FK_70FA2EBFBF396750');
        $this->addSql('ALTER TABLE assignment_answer_check_list_done_tasks DROP FOREIGN KEY FK_6F82122EB16D08A7');
        $this->addSql('ALTER TABLE assignment_answer DROP FOREIGN KEY FK_E2FC6A38D19302F8');
        $this->addSql('ALTER TABLE assignment_checklist DROP FOREIGN KEY FK_917A69C8BF396750');
        $this->addSql('ALTER TABLE assignment_message DROP FOREIGN KEY FK_D5837D86BF396750');
        $this->addSql('ALTER TABLE assignment_notification DROP FOREIGN KEY FK_F32B34F8BF396750');
        $this->addSql('ALTER TABLE assignment_question_list DROP FOREIGN KEY FK_D2BD3B35BF396750');
        $this->addSql('ALTER TABLE assignment_question_numeric DROP FOREIGN KEY FK_B78C4850BF396750');
        $this->addSql('ALTER TABLE assignment_question_range DROP FOREIGN KEY FK_D6CE73FFBF396750');
        $this->addSql('ALTER TABLE assignment_question_text DROP FOREIGN KEY FK_ADFE64EABF396750');
        $this->addSql('ALTER TABLE assignment_question_yes_no DROP FOREIGN KEY FK_D6630618BF396750');
        $this->addSql('ALTER TABLE assignment_standard_task DROP FOREIGN KEY FK_85CC1F5ABF396750');
        $this->addSql('ALTER TABLE assignment_checklist_tasks DROP FOREIGN KEY FK_4BAA92D1B16D08A7');
        $this->addSql('ALTER TABLE assignment_answer_check_list_done_tasks DROP FOREIGN KEY FK_6F82122E8DB60186');
        $this->addSql('ALTER TABLE assignment_question_list_possible_answer DROP FOREIGN KEY FK_8F53778B1E27F6BF');
        $this->addSql('ALTER TABLE assignment_question_answer_list DROP FOREIGN KEY FK_8AECFE59AA334807');
        $this->addSql('ALTER TABLE device_notification_branch DROP FOREIGN KEY FK_89D0C121BF396750');
        $this->addSql('ALTER TABLE device_notification_message DROP FOREIGN KEY FK_77EE7B0EBF396750');
        $this->addSql('ALTER TABLE device_notification_role DROP FOREIGN KEY FK_5F5B5FF7BF396750');
        $this->addSql('ALTER TABLE device_notification_station DROP FOREIGN KEY FK_5E6AB3C0BF396750');
        $this->addSql('ALTER TABLE notification_report DROP FOREIGN KEY FK_8889D9BF396750');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE branch_shift');
        $this->addSql('DROP TABLE branch_station');
        $this->addSql('DROP TABLE card');
        $this->addSql('DROP TABLE history_card_payment');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE date_format');
        $this->addSql('DROP TABLE emergency_phone');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE employee_branch');
        $this->addSql('DROP TABLE employees_branch_shifts');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE file_avatar');
        $this->addSql('DROP TABLE geographical_area');
        $this->addSql('DROP TABLE history_employee_role');
        $this->addSql('DROP TABLE industry_category');
        $this->addSql('DROP TABLE access_token');
        $this->addSql('DROP TABLE auth_code');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE cashier_report');
        $this->addSql('DROP TABLE commodity_report');
        $this->addSql('DROP TABLE end_of_day_report');
        $this->addSql('DROP TABLE end_of_shift_report');
        $this->addSql('DROP TABLE problem_report');
        $this->addSql('DROP TABLE branch_station_role');
        $this->addSql('DROP TABLE branch_station_origin_role');
        $this->addSql('DROP TABLE branch_station_temp_role');
        $this->addSql('DROP TABLE security_recent_login');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE shift_day');
        $this->addSql('DROP TABLE schedule_shifts');
        $this->addSql('DROP TABLE subcategory');
        $this->addSql('DROP TABLE time_zone');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE users_groups');
        $this->addSql('DROP TABLE user_admin');
        $this->addSql('DROP TABLE user_branch_manager');
        $this->addSql('DROP TABLE user_co_manager');
        $this->addSql('DROP TABLE user_device');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE user_office_employee');
        $this->addSql('DROP TABLE user_owner');
        $this->addSql('DROP TABLE user_supervisor');
        $this->addSql('DROP TABLE assignment_answer');
        $this->addSql('DROP TABLE assignment_answer_check_list');
        $this->addSql('DROP TABLE assignment_answer_check_list_done_tasks');
        $this->addSql('DROP TABLE assignment_question_answer_list');
        $this->addSql('DROP TABLE assignment_answer_question_numeric');
        $this->addSql('DROP TABLE assignment_answer_question_range');
        $this->addSql('DROP TABLE assignment_answer_question_text');
        $this->addSql('DROP TABLE assignment_answer_question_yes_no');
        $this->addSql('DROP TABLE assignment_answer_standard_task');
        $this->addSql('DROP TABLE `assignment`');
        $this->addSql('DROP TABLE assignment_checklist');
        $this->addSql('DROP TABLE assignment_checklist_tasks');
        $this->addSql('DROP TABLE assignment_message');
        $this->addSql('DROP TABLE assignment_notification');
        $this->addSql('DROP TABLE assignment_question_list');
        $this->addSql('DROP TABLE assignment_question_list_possible_answer');
        $this->addSql('DROP TABLE assignment_question_numeric');
        $this->addSql('DROP TABLE assignment_question_range');
        $this->addSql('DROP TABLE assignment_question_text');
        $this->addSql('DROP TABLE assignment_question_yes_no');
        $this->addSql('DROP TABLE assignment_standard_task');
        $this->addSql('DROP TABLE device_notification');
        $this->addSql('DROP TABLE device_notification_branch');
        $this->addSql('DROP TABLE device_notification_message');
        $this->addSql('DROP TABLE device_notification_role');
        $this->addSql('DROP TABLE device_notification_station');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_report');
    }
}
