<?php

namespace AssignmentsBundle\Repository\Assignment\Question;

/**
 * AbstractQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
