<?php

namespace AssignmentsBundle\Repository\Notification\Repeat;

/**
 * RepeatWeekDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepeatWeekDayRepository extends \Doctrine\ORM\EntityRepository
{
}
