<?php

namespace ApiBundle\Repository\Report;

use ApiBundle\Entity\BranchStation;

/**
 * CashierReportGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashierReportGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $group
     * @param BranchStation $station
     * @return mixed
     */
    public function getReportsByGroup($group, $station = null, $branch = null)
    {
        $qb = $this->createQueryBuilder('CashierReportGroup');
        $qb->innerJoin('CashierReportGroup.cashier_report', 'cr')
            ->innerJoin('cr.branch_station', 'bs')
            ->innerJoin('bs.branch', 'b');

        if(!empty($station)) {
            $qb->andWhere('cr.branch_station = :station')
                ->setParameter('station', $station);
        }
        if(!empty($branch)) {
            $qb->andWhere('bs.branch = :branch')
                ->setParameter('branch', $branch);
        }

        $qb->andWhere('CashierReportGroup.group_report = :group')
            ->setParameter('group', $group);

        $query = $qb->getQuery();
        return $query->getResult();
    }

    /**
     * @param $date_created
     * @param BranchStation $station
     * @return mixed
     */
    public function getGroupReportsByDate($date_created, $station = null, $branch = null)
    {
        $qb = $this->createQueryBuilder('CashierReportGroup');
        $qb->select("CashierReportGroup.group_report")
            ->innerJoin('CashierReportGroup.cashier_report', 'cr')
            ->innerJoin('cr.branch_station', 'bs')
            ->innerJoin('bs.branch', 'b');

        if(!empty($station)) {
            $qb->andWhere('cr.branch_station = :station')
                ->setParameter('station', $station);
        }
        if(!empty($branch)) {
            $qb->andWhere('bs.branch = :branch')
                ->setParameter('branch', $branch);
        }

        $qb->andWhere('DATE(:date) = DATE(cr.created)')
            ->setParameter(':date', $date_created);

        $qb->groupBy('CashierReportGroup.group_report');
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
