<?php

namespace ApiBundle\Repository\Report;

/**
 * EndOfDayReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndOfDayReportRepository extends \Doctrine\ORM\EntityRepository
{
}
