<?php

namespace AssignmentsBundle\Repository\Assignment\Repeat;

/**
 * AssignmentRepeatHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentRepeatHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
