<?php

namespace AssignmentsBundle\Repository\Assignment\Repeat;

/**
 * RepeatMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepeatMonthRepository extends \Doctrine\ORM\EntityRepository
{
}
