<?php

namespace AssignmentsBundle\Repository\Assignment\Repeat;

/**
 * RepeatMonthDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepeatMonthDayRepository extends \Doctrine\ORM\EntityRepository
{
}
