<?php

namespace ApiBundle\Repository;

/**
 * BranchStationRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchStationRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
