<?php

namespace ApiBundle\Repository;

/**
 * BranchStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchStationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsedPins()
    {
        $qb = $this->createQueryBuilder('BranchStation');
        $qb -> select('BranchStation.pin')
            -> where('BranchStation.pin_expire > :time')
        ->setParameter('time', new \DateTime("now"));

        return array_column($qb->getQuery()->getResult(),"pin");
    }
}
