<?php

namespace ApiBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersByType($type) {
        $qb = $this->createQueryBuilder('Company');
        $qb->innerJoin('Company.users', 'User')
            ->where('User.type = :user_type')
            ->setParameter('user_type', $type);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
