<?php

namespace ApiBundle\Repository;

/**
 * DateFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
