<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns filtered list employees.
     * @param $entityAlias
     * @return QueryBuilder
     */
    public function searchEmployees($entityAlias)
    {
        $qb = $this->createQueryBuilder($entityAlias);

        $qb->innerJoin($entityAlias.'.branches', 'b');

        return $qb;
    }
}
