<?php

namespace ApiBundle\Repository;

/**
 * FamilyStatusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyStatusesRepository extends \Doctrine\ORM\EntityRepository
{
}
