<?php

namespace ApiBundle\Repository;

/**
 * GeographicalAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeographicalAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
