<?php

namespace ApiBundle\Repository;

/**
 * IndustryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
