<?php

namespace ApiBundle\Repository;

/**
 * ShiftDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftDayRepository extends \Doctrine\ORM\EntityRepository
{
}
