<?php

namespace ApiBundle\Repository;

/**
 * TimeZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
