<?php

namespace ApiBundle\Repository;

/**
 * TimeFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
