<?php

namespace ApiBundle\Repository;

/**
 * UTCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UTCRepository extends \Doctrine\ORM\EntityRepository
{
}
