<?php

namespace ApiBundle\Repository\Recommendations;

/**
 * RecommendationsStationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendationsStationsRepository extends \Doctrine\ORM\EntityRepository
{
}
