<?php

namespace ApiBundle\Repository\Recommendations;

/**
 * RecommendationsRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendationsRolesRepository extends \Doctrine\ORM\EntityRepository
{
}
