<?php

namespace ApiBundle\Repository\Role;

/**
 * BranchStationOriginRole
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchStationOriginRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
