<?php

namespace ApiBundle\Repository\Role;

/**
 * BranchStationTempRole
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchStationTempRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
