<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerCheckListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerCheckListRepository extends \Doctrine\ORM\EntityRepository
{
}
