<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerCheckListDoneTasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerCheckListDoneTasksRepository extends \Doctrine\ORM\EntityRepository
{
}
