<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerQuestionYesNoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerQuestionYesNoRepository extends \Doctrine\ORM\EntityRepository
{
}
