<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerQuestionTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerQuestionTextRepository extends \Doctrine\ORM\EntityRepository
{
}
