<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerQuestionNumericRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerQuestionNumericRepository extends \Doctrine\ORM\EntityRepository
{
}
