<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerQuestionRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerQuestionRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
