<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerStandardTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerStandardTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
