<?php

namespace AssignmentsBundle\Repository\Answer;

/**
 * AnswerQuestionAnswerListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerQuestionAnswerListRepository extends \Doctrine\ORM\EntityRepository
{
}
