<?php

namespace ApiBundle\Repository\Security;

/**
 * RecentLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecentLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
