<?php

namespace ApiBundle\Repository\Security;

/**
 * WhiteCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhiteCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
