<?php

namespace ApiBundle\Repository\Notification;

/**
 * CustomNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
